Калашников О.Ю. 3530901/10005
Saloed/gradle-task pull request #14
Opened 2022-03-01 11:30 UTC by s1ckoleg

2022-03-01 12:24 UTC, Saloed requested changes
А зачем вам понадобилась директория `lib`  и всё её содержимое?

2022-03-01 12:24 UTC, Saloed commented on build.gradle.kts
> +    `java-library`
А зачем вам `java-library`?

2022-03-01 14:08 UTC, s1ckoleg commented on build.gradle.kts
> +    `java-library`
Идея выдала подсказку, вроде было что-то про конфигурацию Котлина, и сама создала `lib`. 

Насчёт `java-library` — я смотрел дополнительно туториалы по грейдлу и там делали таким образом. Видимо я что-то неправильно понял и `java-library` не нужно?

2022-03-03 09:22 UTC, Saloed commented on build.gradle.kts
> +    `java-library`
`java-library` это плагин, который добавляет возможности, которые нужны только в том случае, если вы собираете библиотеку. Вам это не нужно.

2022-03-04 12:29 UTC, s1ckoleg commented on build.gradle.kts
> +    `java-library`
Понял, спасибо, исправил и запушил

2022-03-04 15:46 UTC, Saloed requested changes
Директория lib и всё её содержимое всё ещё в репозитории

2022-03-05 14:13 UTC, closed without merging