Иванов Я.А., гр. 3530901/10003
Saloed/gradle-task pull request #41
Opened 2022-03-04 10:55 UTC by vitaya-para

2022-03-04 15:51 UTC, Saloed requested changes

2022-03-04 15:51 UTC, Saloed commented on build.gradle.kts
> +    distributionType = Wrapper.DistributionType.ALL
А зачем вам это понадобилось?

2022-03-04 15:51 UTC, Saloed commented on build.gradle.kts
> +    java
А зачем вам `java`? В проекте этого языка нет.

2022-03-04 17:11 UTC, vitaya-para commented on build.gradle.kts
> +    distributionType = Wrapper.DistributionType.ALL
Чтобы перед пушем проверить локально корректность работы gradlew wrapper

2022-03-04 17:12 UTC, vitaya-para commented on build.gradle.kts
> +    java
Согласен, строка 3 - лишняя. Ее нужно убрать в следующем коммите или можно оставить?

2022-03-05 14:11 UTC, Saloed approved these changes

2022-03-05 14:12 UTC, closed without merging